-- Showcase V2: extra columns on app_user for the FIX311 Users panel.
-- Adds:
--   email       — admin-set address (FIX311.2.1.2). Nullable until V2
--                 redemption flow lands; legacy synthetic addresses
--                 are still valid via Supabase Auth.
--   access_code — 6-digit invitation code generated by the admin
--                 (FIX311.2.1.4). Stored as text to preserve leading
--                 zeros. Backfilled for existing users so the column
--                 isn't blank in the panel on first deploy.
-- Idempotent: safe to re-run.


alter table app_user
  add column if not exists email       text,
  add column if not exists access_code text;

-- Backfill existing rows with a fresh 6-digit code if they don't
-- already have one. Existing real users keep whatever code was set
-- on a previous run.
update app_user
   set access_code = lpad(floor(random() * 1000000)::int::text, 6, '0')
 where access_code is null;
